name: Javaworkflow
on: workflow_dispatch
jobs:
  Testing:
   runs-on: ubuntu-latest
   steps:
    - name: Clone the repo
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Install Dependencies
      run: mvn clean install
      
